import crypto from "node:crypto";
import { Pool } from "pg";
import { config } from "./config.js";
import { BUILTIN_TOOLS } from "./tools.js";
import type {
  AdminActivity, AdminAgent, AdminConversation, AdminDeployment, AdminKnowledge, AdminTool, AdminUsageEvent, AuditEvent, Agent, AgentConnection, AgentVersion, AiProvider, AiProviderAdapter, AiProviderSettings, ApiKeyRecord, Conversation, ConversationStatus, Deployment, EmailCampaign, EmailCampaignRow, EmailReplyEvent, EmailSettings, KnowledgeSource, Message, Store, StoredAiProvider, UsageEvent,
} from "./types.js";

const now = () => new Date().toISOString();
const id = (prefix: string) => `${prefix}_${crypto.randomBytes(8).toString("hex")}`;

export async function ensureSchema(pool: Pool): Promise<void> {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS gbolix_agents (
      id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', instructions TEXT NOT NULL, tone TEXT NOT NULL DEFAULT 'warm, concise, and helpful', model TEXT NOT NULL, level INTEGER NOT NULL DEFAULT 1, status TEXT NOT NULL DEFAULT 'draft', welcome_message TEXT NOT NULL DEFAULT 'Hi! How can I help you today?', enabled_tools JSONB NOT NULL DEFAULT '[]'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS gbolix_agents_workspace_idx ON gbolix_agents(workspace_id);
    ALTER TABLE gbolix_agents ADD COLUMN IF NOT EXISTS level INTEGER NOT NULL DEFAULT 1;
    UPDATE gbolix_agents SET level=3 WHERE enabled_tools <> '[]'::jsonb AND level=1;
    UPDATE gbolix_agents SET level=2 WHERE level=1 AND EXISTS (SELECT 1 FROM gbolix_knowledge WHERE gbolix_knowledge.agent_id=gbolix_agents.id);
    UPDATE gbolix_agents SET status='draft' WHERE status IS NULL;
    ALTER TABLE gbolix_agents ALTER COLUMN status SET DEFAULT 'draft';
    ALTER TABLE gbolix_agents ALTER COLUMN status SET NOT NULL;
    CREATE TABLE IF NOT EXISTS gbolix_agent_versions (id TEXT PRIMARY KEY, agent_id TEXT NOT NULL REFERENCES gbolix_agents(id) ON DELETE CASCADE, workspace_id TEXT NOT NULL, version INTEGER NOT NULL, config JSONB NOT NULL, created_by TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(agent_id, version));
    CREATE INDEX IF NOT EXISTS gbolix_agent_versions_agent_idx ON gbolix_agent_versions(agent_id, workspace_id, version DESC);
    CREATE TABLE IF NOT EXISTS gbolix_knowledge (id TEXT PRIMARY KEY, agent_id TEXT NOT NULL REFERENCES gbolix_agents(id) ON DELETE CASCADE, workspace_id TEXT NOT NULL, title TEXT NOT NULL, content TEXT NOT NULL, source_type TEXT NOT NULL DEFAULT 'text', status TEXT NOT NULL DEFAULT 'ready', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE INDEX IF NOT EXISTS gbolix_knowledge_agent_idx ON gbolix_knowledge(agent_id, workspace_id);
    CREATE TABLE IF NOT EXISTS gbolix_conversations (id TEXT PRIMARY KEY, agent_id TEXT NOT NULL REFERENCES gbolix_agents(id) ON DELETE CASCADE, workspace_id TEXT NOT NULL, channel TEXT NOT NULL, visitor_key TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE INDEX IF NOT EXISTS gbolix_conversations_agent_idx ON gbolix_conversations(agent_id, workspace_id, updated_at DESC);
    CREATE TABLE IF NOT EXISTS gbolix_messages (id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL REFERENCES gbolix_conversations(id) ON DELETE CASCADE, role TEXT NOT NULL, content TEXT NOT NULL, tool_name TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE INDEX IF NOT EXISTS gbolix_messages_conversation_idx ON gbolix_messages(conversation_id, created_at);
    CREATE TABLE IF NOT EXISTS gbolix_deployments (id TEXT PRIMARY KEY, agent_id TEXT NOT NULL REFERENCES gbolix_agents(id) ON DELETE CASCADE, workspace_id TEXT NOT NULL, channel TEXT NOT NULL, allowed_origin TEXT, token_prefix TEXT NOT NULL, public_token_hash TEXT NOT NULL UNIQUE, status TEXT NOT NULL DEFAULT 'active', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE INDEX IF NOT EXISTS gbolix_deployments_token_idx ON gbolix_deployments(public_token_hash);
    ALTER TABLE gbolix_deployments ADD COLUMN IF NOT EXISTS encrypted_public_token TEXT;
    CREATE TABLE IF NOT EXISTS gbolix_api_keys (id TEXT PRIMARY KEY, agent_id TEXT NOT NULL REFERENCES gbolix_agents(id) ON DELETE CASCADE, workspace_id TEXT NOT NULL, key_prefix TEXT NOT NULL, key_hash TEXT NOT NULL UNIQUE, status TEXT NOT NULL DEFAULT 'active', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), last_used_at TIMESTAMPTZ);
    CREATE TABLE IF NOT EXISTS gbolix_agent_connections (id TEXT PRIMARY KEY, agent_id TEXT NOT NULL REFERENCES gbolix_agents(id) ON DELETE CASCADE, workspace_id TEXT NOT NULL, kind TEXT NOT NULL, provider TEXT NOT NULL, name TEXT NOT NULL, endpoint TEXT, method TEXT, auth_type TEXT, encrypted_secret TEXT, headers JSONB NOT NULL DEFAULT '{}'::jsonb, parameters JSONB NOT NULL DEFAULT '{}'::jsonb, status TEXT NOT NULL DEFAULT 'connected', permissions JSONB NOT NULL DEFAULT '[]'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE INDEX IF NOT EXISTS gbolix_agent_connections_agent_idx ON gbolix_agent_connections(agent_id, workspace_id, updated_at DESC);
    CREATE TABLE IF NOT EXISTS gbolix_email_settings (agent_id TEXT PRIMARY KEY REFERENCES gbolix_agents(id) ON DELETE CASCADE, workspace_id TEXT NOT NULL, reply_mode TEXT NOT NULL DEFAULT 'off', reply_scope TEXT NOT NULL DEFAULT 'agent_sent', matching_query TEXT NOT NULL DEFAULT '', updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS gbolix_ai_provider_settings (agent_id TEXT PRIMARY KEY REFERENCES gbolix_agents(id) ON DELETE CASCADE, workspace_id TEXT NOT NULL, provider_order JSONB NOT NULL DEFAULT '["gemini","openai"]'::jsonb, models JSONB NOT NULL DEFAULT '{}'::jsonb, fallback_enabled BOOLEAN NOT NULL DEFAULT TRUE, auto_update_models BOOLEAN NOT NULL DEFAULT TRUE, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS gbolix_ai_providers (id TEXT PRIMARY KEY, name TEXT NOT NULL, adapter TEXT NOT NULL, base_url TEXT NOT NULL, encrypted_api_key TEXT, default_model TEXT NOT NULL, priority INTEGER NOT NULL DEFAULT 100, enabled BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    ALTER TABLE gbolix_ai_providers ADD COLUMN IF NOT EXISTS priority INTEGER NOT NULL DEFAULT 100;
    CREATE INDEX IF NOT EXISTS gbolix_ai_providers_enabled_idx ON gbolix_ai_providers(enabled, priority ASC, updated_at DESC);
    CREATE TABLE IF NOT EXISTS gbolix_email_campaigns (id TEXT PRIMARY KEY, agent_id TEXT NOT NULL REFERENCES gbolix_agents(id) ON DELETE CASCADE, workspace_id TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'queued', subject_template TEXT NOT NULL, body_template TEXT NOT NULL, message_mode TEXT NOT NULL DEFAULT 'shared', total_rows INTEGER NOT NULL DEFAULT 0, sent_rows INTEGER NOT NULL DEFAULT 0, failed_rows INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE INDEX IF NOT EXISTS gbolix_email_campaigns_agent_idx ON gbolix_email_campaigns(agent_id, workspace_id, created_at DESC);
    CREATE TABLE IF NOT EXISTS gbolix_email_campaign_rows (id TEXT PRIMARY KEY, campaign_id TEXT NOT NULL REFERENCES gbolix_email_campaigns(id) ON DELETE CASCADE, row_number INTEGER NOT NULL, email TEXT NOT NULL, data JSONB NOT NULL DEFAULT '{}'::jsonb, subject TEXT NOT NULL, body TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'queued', message_id TEXT, thread_id TEXT, error TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(campaign_id, row_number));
    CREATE INDEX IF NOT EXISTS gbolix_email_campaign_rows_campaign_idx ON gbolix_email_campaign_rows(campaign_id, row_number);
    CREATE TABLE IF NOT EXISTS gbolix_email_reply_events (id TEXT PRIMARY KEY, agent_id TEXT NOT NULL REFERENCES gbolix_agents(id) ON DELETE CASCADE, workspace_id TEXT NOT NULL, gmail_message_id TEXT NOT NULL, thread_id TEXT NOT NULL, from_email TEXT, subject TEXT, received_at TIMESTAMPTZ, body TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', reply_body TEXT, reply_message_id TEXT, error TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(agent_id, gmail_message_id));
    CREATE INDEX IF NOT EXISTS gbolix_email_reply_events_agent_idx ON gbolix_email_reply_events(agent_id, workspace_id, updated_at DESC);
    CREATE TABLE IF NOT EXISTS gbolix_usage_events (request_id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, agent_id TEXT NOT NULL REFERENCES gbolix_agents(id) ON DELETE CASCADE, conversation_id TEXT NOT NULL, model TEXT NOT NULL, input_tokens INTEGER NOT NULL DEFAULT 0, output_tokens INTEGER NOT NULL DEFAULT 0, tool_calls INTEGER NOT NULL DEFAULT 0, credits INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL, channel TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE INDEX IF NOT EXISTS gbolix_usage_workspace_idx ON gbolix_usage_events(workspace_id, created_at DESC);
    CREATE TABLE IF NOT EXISTS gbolix_audit_logs (id TEXT PRIMARY KEY, actor_id TEXT NOT NULL, workspace_id TEXT NOT NULL, action TEXT NOT NULL, target_type TEXT NOT NULL, target_id TEXT NOT NULL, metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE INDEX IF NOT EXISTS gbolix_audit_workspace_idx ON gbolix_audit_logs(workspace_id, created_at DESC);
  `);
}

class MemoryStore implements Store {
  private agents = new Map<string, Agent>(); private aiProviderSettings = new Map<string, AiProviderSettings>(); private aiProviders = new Map<string, StoredAiProvider>(); private knowledge = new Map<string, KnowledgeSource>(); private conversations = new Map<string, Conversation>(); private messages = new Map<string, Message>(); private deployments = new Map<string, Deployment & { tokenHash: string; encryptedToken?: string }>(); private apiKeys = new Map<string, ApiKeyRecord>(); private connections = new Map<string, AgentConnection & { encryptedSecret?: string; headers?: Record<string, string>; parameters?: Record<string, string> }>(); private usage = new Map<string, UsageEvent>(); private audits = new Map<string, AuditEvent>(); private agentVersions = new Map<string, AgentVersion>(); private emailSettings = new Map<string, EmailSettings>(); private emailCampaigns = new Map<string, EmailCampaign>(); private emailCampaignRows = new Map<string, EmailCampaignRow>(); private emailReplyEvents = new Map<string, EmailReplyEvent>();
  async listAgents(workspaceId: string) { return [...this.agents.values()].filter((item) => item.workspaceId === workspaceId).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)); }
  async createAgentVersion(input: Omit<AgentVersion, "id" | "createdAt">) { const item = { ...input, id: id("ver"), createdAt: now() }; this.agentVersions.set(item.id, item); return item; }
  async listAgentVersions(agentId: string, workspaceId: string) { return [...this.agentVersions.values()].filter((item) => item.agentId === agentId && item.workspaceId === workspaceId).sort((a, b) => b.version - a.version); }
  async restoreAgentVersion(versionId: string, agentId: string, workspaceId: string) { const version = this.agentVersions.get(versionId); if (!version || version.agentId !== agentId || version.workspaceId !== workspaceId) return undefined; return this.updateAgent(agentId, workspaceId, version.config); }
  async getAgent(agentId: string) { return this.agents.get(agentId); }
  async createAgent(input: Omit<Agent, "id" | "createdAt" | "updatedAt">) { const item = { ...input, id: id("agent"), createdAt: now(), updatedAt: now() }; this.agents.set(item.id, item); return item; }
  async updateAgent(agentId: string, workspaceId: string, patch: Partial<Pick<Agent, "name" | "description" | "instructions" | "tone" | "model" | "level" | "status" | "welcomeMessage" | "enabledTools">>) { const current = this.agents.get(agentId); if (!current || current.workspaceId !== workspaceId) return undefined; const item = { ...current, ...patch, status: current.status ?? "draft", updatedAt: now() }; this.agents.set(agentId, item); return item; }
  async listKnowledge(agentId: string, workspaceId: string) { return [...this.knowledge.values()].filter((item) => item.agentId === agentId && item.status === "ready" && this.agents.get(agentId)?.workspaceId === workspaceId).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)); }
  async addKnowledge(input: Omit<KnowledgeSource, "id" | "createdAt" | "updatedAt">) { const item = { ...input, id: id("know"), createdAt: now(), updatedAt: now() }; this.knowledge.set(item.id, item); return item; }
  async deleteKnowledge(knowledgeId: string, agentId: string, workspaceId: string) { const item = this.knowledge.get(knowledgeId); if (!item || item.agentId !== agentId || this.agents.get(agentId)?.workspaceId !== workspaceId) return false; this.knowledge.delete(knowledgeId); return true; }
  async getConversation(conversationId: string, workspaceId: string) { const item = this.conversations.get(conversationId); return item?.workspaceId === workspaceId ? item : undefined; }
  async listConversations(agentId: string, workspaceId: string) { return [...this.conversations.values()].filter((item) => item.agentId === agentId && item.workspaceId === workspaceId).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)); }
  async createConversation(input: Omit<Conversation, "id" | "createdAt" | "updatedAt">) { const item = { ...input, id: id("conv"), createdAt: now(), updatedAt: now() }; this.conversations.set(item.id, item); return item; }
  async touchConversation(conversationId: string, status?: ConversationStatus) { const item = this.conversations.get(conversationId); if (item) this.conversations.set(conversationId, { ...item, ...(status ? { status } : {}), updatedAt: now() }); }
  async listMessages(conversationId: string) { return [...this.messages.values()].filter((item) => item.conversationId === conversationId).sort((a, b) => a.createdAt.localeCompare(b.createdAt)); }
  async addMessage(input: Omit<Message, "id" | "createdAt">) { const item = { ...input, id: id("msg"), createdAt: now() }; this.messages.set(item.id, item); return item; }
  async createDeployment(input: Omit<Deployment, "id" | "createdAt" | "updatedAt">) { const raw = crypto.randomBytes(24).toString("base64url"); const item = { ...input, id: id("dep"), tokenPrefix: `gblx_${raw.slice(0, 8)}`, tokenHash: hash(raw), encryptedToken: sealDeploymentToken(raw), createdAt: now(), updatedAt: now() }; this.deployments.set(item.id, item); const { tokenHash: _tokenHash, encryptedToken: _encryptedToken, ...deployment } = item; return { ...deployment, plaintextToken: raw }; }
  async listDeployments(agentId: string, workspaceId: string) { return [...this.deployments.values()].filter((item) => item.agentId === agentId && item.workspaceId === workspaceId).map(({ tokenHash: _tokenHash, encryptedToken: _encryptedToken, ...item }) => item); }
  async getDeploymentByToken(token: string) { const match = [...this.deployments.values()].find((item) => item.tokenHash === hash(token) && item.status === "active"); if (!match) return undefined; const { tokenHash: _tokenHash, encryptedToken: _encryptedToken, ...deployment } = match; const agent = this.agents.get(match.agentId); return agent ? { deployment, agent } : undefined; }
  async getDeploymentArtifact(deploymentId: string, agentId: string, workspaceId: string) { const item = this.deployments.get(deploymentId); if (!item || item.agentId !== agentId || item.workspaceId !== workspaceId || item.status !== "active") return undefined; let raw = item.encryptedToken ? openDeploymentToken(item.encryptedToken) : undefined; if (!raw) { raw = crypto.randomBytes(24).toString("base64url"); this.deployments.set(item.id, { ...item, tokenPrefix: `gblx_${raw.slice(0, 8)}`, tokenHash: hash(raw), encryptedToken: sealDeploymentToken(raw), updatedAt: now() }); } const current = this.deployments.get(item.id)!; const { tokenHash: _tokenHash, encryptedToken: _encryptedToken, ...deployment } = current; return { deployment, plaintextToken: raw }; }
  async revokeDeployment(deploymentId: string, agentId: string, workspaceId: string) { const item = this.deployments.get(deploymentId); if (!item || item.agentId !== agentId || item.workspaceId !== workspaceId) return false; this.deployments.set(deploymentId, { ...item, status: "revoked", updatedAt: now() }); return true; }
  async createApiKey(input: Omit<ApiKeyRecord, "id" | "createdAt">) { const item = { ...input, id: id("key"), createdAt: now() }; this.apiKeys.set(item.id, item); return item; }
  async getApiKeyByHash(keyHash: string) { const item = [...this.apiKeys.values()].find((value) => value.keyHash === keyHash && value.status === "active"); if (item) item.lastUsedAt = now(); return item; }
  async listApiKeys(agentId: string, workspaceId: string) { return [...this.apiKeys.values()].filter((item) => item.agentId === agentId && item.workspaceId === workspaceId).map((item) => ({ ...item, keyHash: "" })); }
  async revokeApiKey(id: string, agentId: string, workspaceId: string) { const item = this.apiKeys.get(id); if (!item || item.agentId !== agentId || item.workspaceId !== workspaceId) return false; this.apiKeys.set(id, { ...item, status: "revoked" }); return true; }
  async createConnection(input: { agentId: string; workspaceId: string; kind: AgentConnection["kind"]; provider: string; name: string; endpoint?: string; method?: AgentConnection["method"]; authType?: AgentConnection["authType"]; encryptedSecret?: string; headers?: Record<string, string>; parameters?: Record<string, string>; permissions: string[] }) { const item = { ...input, id: id("conn"), status: "connected" as const, createdAt: now(), updatedAt: now() }; this.connections.set(item.id, item); const { encryptedSecret: _secret, headers: _headers, parameters: _parameters, ...publicItem } = item; return publicItem; }
  async listConnections(agentId: string, workspaceId: string) { return [...this.connections.values()].filter((item) => item.agentId === agentId && item.workspaceId === workspaceId).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)).map(({ encryptedSecret: _secret, headers: _headers, parameters: _parameters, ...item }) => item); }
  async getConnection(connectionId: string, agentId: string, workspaceId: string) { const item = this.connections.get(connectionId); return item && item.agentId === agentId && item.workspaceId === workspaceId ? item : undefined; }
  async updateConnectionSecret(connectionId: string, agentId: string, workspaceId: string, encryptedSecret: string) { const item = this.connections.get(connectionId); if (!item || item.agentId !== agentId || item.workspaceId !== workspaceId) return false; this.connections.set(connectionId, { ...item, encryptedSecret, updatedAt: now() }); return true; }
  async deleteConnection(id: string, agentId: string, workspaceId: string) { const item = this.connections.get(id); if (!item || item.agentId !== agentId || item.workspaceId !== workspaceId) return false; this.connections.delete(id); return true; }
  async listAgentsWithEmailAutomation() { return [...this.emailSettings.values()].filter((setting) => setting.replyMode !== "off").map((setting) => this.agents.get(setting.agentId)).filter((agent): agent is Agent => Boolean(agent)); }
  async getAiProviderSettings(agentId: string, workspaceId: string) { const item = this.aiProviderSettings.get(agentId); return item?.workspaceId === workspaceId ? item : undefined; }
  async upsertAiProviderSettings(input: Omit<AiProviderSettings, "updatedAt">) { const item = { ...input, updatedAt: now() }; this.aiProviderSettings.set(input.agentId, item); return item; }
  async listAiProviders() { return [...this.aiProviders.values()].map(({ encryptedApiKey: _secret, ...item }) => item).sort((a, b) => a.priority - b.priority || a.name.localeCompare(b.name)); }
  async listAiProviderSecrets() { return [...this.aiProviders.values()].sort((a, b) => a.priority - b.priority || a.name.localeCompare(b.name)); }
  async getAiProvider(providerId: string) { return this.aiProviders.get(providerId); }
  async upsertAiProvider(input: { id: string; name: string; adapter: AiProviderAdapter; baseUrl: string; encryptedApiKey?: string; defaultModel: string; priority: number; enabled: boolean }) { const current = this.aiProviders.get(input.id); const item: StoredAiProvider = { ...input, encryptedApiKey: input.encryptedApiKey ?? current?.encryptedApiKey, apiKeyConfigured: Boolean(input.encryptedApiKey ?? current?.encryptedApiKey), createdAt: current?.createdAt ?? now(), updatedAt: now() }; this.aiProviders.set(item.id, item); const { encryptedApiKey: _secret, ...publicItem } = item; return publicItem; }
  async deleteAiProvider(providerId: string) { return this.aiProviders.delete(providerId); }
  async getEmailSettings(agentId: string, workspaceId: string) { const item = this.emailSettings.get(agentId); return item?.workspaceId === workspaceId ? item : undefined; }
  async upsertEmailSettings(input: Omit<EmailSettings, "updatedAt">) { const item = { ...input, updatedAt: now() }; this.emailSettings.set(input.agentId, item); return item; }
  async createEmailCampaign(input: Omit<EmailCampaign, "id" | "createdAt" | "updatedAt" | "sentRows" | "failedRows">) { const item = { ...input, id: id("campaign"), sentRows: 0, failedRows: 0, createdAt: now(), updatedAt: now() }; this.emailCampaigns.set(item.id, item); return item; }
  async listEmailCampaigns(agentId: string, workspaceId: string, limit: number) { return [...this.emailCampaigns.values()].filter((item) => item.agentId === agentId && item.workspaceId === workspaceId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, limit); }
  async getEmailCampaign(campaignId: string, agentId: string, workspaceId: string) { const item = this.emailCampaigns.get(campaignId); return item?.agentId === agentId && item.workspaceId === workspaceId ? item : undefined; }
  async updateEmailCampaign(campaignId: string, agentId: string, workspaceId: string, patch: Partial<Pick<EmailCampaign, "status" | "sentRows" | "failedRows" | "totalRows">>) { const item = await this.getEmailCampaign(campaignId, agentId, workspaceId); if (!item) return undefined; const updated = { ...item, ...patch, updatedAt: now() }; this.emailCampaigns.set(campaignId, updated); return updated; }
  async addEmailCampaignRows(rows: Array<Omit<EmailCampaignRow, "id" | "createdAt" | "updatedAt">>) { const items = rows.map((input) => { const item = { ...input, id: id("campaign_row"), createdAt: now(), updatedAt: now() }; this.emailCampaignRows.set(item.id, item); return item; }); return items; }
  async listEmailCampaignRows(campaignId: string, limit: number) { return [...this.emailCampaignRows.values()].filter((item) => item.campaignId === campaignId).sort((a, b) => a.rowNumber - b.rowNumber).slice(0, limit); }
  async updateEmailCampaignRow(rowId: string, campaignId: string, patch: Partial<Pick<EmailCampaignRow, "status" | "messageId" | "threadId" | "error">>) { const item = this.emailCampaignRows.get(rowId); if (!item || item.campaignId !== campaignId) return undefined; const updated = { ...item, ...patch, updatedAt: now() }; this.emailCampaignRows.set(rowId, updated); return updated; }
  async getEmailReplyEvent(agentId: string, gmailMessageId: string) { return [...this.emailReplyEvents.values()].find((item) => item.agentId === agentId && item.gmailMessageId === gmailMessageId); }
  async createEmailReplyEvent(input: Omit<EmailReplyEvent, "id" | "createdAt" | "updatedAt">) { const existing = await this.getEmailReplyEvent(input.agentId, input.gmailMessageId); if (existing) return existing; const item = { ...input, id: id("reply"), createdAt: now(), updatedAt: now() }; this.emailReplyEvents.set(item.id, item); return item; }
  async updateEmailReplyEvent(eventId: string, agentId: string, patch: Partial<Pick<EmailReplyEvent, "status" | "replyBody" | "replyMessageId" | "error">>) { const item = this.emailReplyEvents.get(eventId); if (!item || item.agentId !== agentId) return undefined; const updated = { ...item, ...patch, updatedAt: now() }; this.emailReplyEvents.set(eventId, updated); return updated; }
  async listEmailReplyEvents(agentId: string, workspaceId: string, limit: number) { return [...this.emailReplyEvents.values()].filter((item) => item.agentId === agentId && item.workspaceId === workspaceId).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)).slice(0, limit); }
  async addUsageEvent(event: UsageEvent) { const existing = this.usage.get(event.requestId); if (existing) return existing; this.usage.set(event.requestId, event); return event; }
  async listUsage(agentId: string, workspaceId: string, limit: number) { return [...this.usage.values()].filter((item) => item.agentId === agentId && item.workspaceId === workspaceId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, limit); }
  async addAuditEvent(event: Omit<AuditEvent, "id" | "createdAt">) { const item = { ...event, id: id("audit"), createdAt: now() }; this.audits.set(item.id, item); return item; }
  async listAudit(workspaceId: string, limit: number) { return [...this.audits.values()].filter((item) => item.workspaceId === workspaceId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, limit); }
  async adminOverview() { const events = [...this.usage.values()]; return { customers: new Set([...this.agents.values()].map((item) => item.workspaceId)).size, agents: this.agents.size, responses: events.filter((item) => item.status === "completed").length, creditsUsed: events.reduce((sum, item) => sum + item.credits, 0), deployments: [...this.deployments.values()].filter((item) => item.status === "active").length }; }
  async adminCustomers(limit: number) { const ids = new Set([...this.agents.values()].map((item) => item.workspaceId)); return [...ids].slice(0, limit).map((workspaceId) => { const agents = [...this.agents.values()].filter((item) => item.workspaceId === workspaceId); const events = [...this.usage.values()].filter((item) => item.workspaceId === workspaceId); return { workspaceId, agents: agents.length, responses: events.filter((item) => item.status === "completed").length, creditsUsed: events.reduce((sum, item) => sum + item.credits, 0) }; }); }
  async adminAgents(limit: number) { return [...this.agents.values()].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)).slice(0, limit).map((agent) => ({ ...agent, knowledgeCount: [...this.knowledge.values()].filter((item) => item.agentId === agent.id).length, conversationCount: [...this.conversations.values()].filter((item) => item.agentId === agent.id).length, responses: [...this.usage.values()].filter((item) => item.agentId === agent.id && item.status === "completed").length, creditsUsed: [...this.usage.values()].filter((item) => item.agentId === agent.id).reduce((sum, item) => sum + item.credits, 0), deploymentCount: [...this.deployments.values()].filter((item) => item.agentId === agent.id).length })); }
  async adminConversations(limit: number) { return [...this.conversations.values()].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)).slice(0, limit).map((conversation) => { const messages = [...this.messages.values()].filter((item) => item.conversationId === conversation.id).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); return { ...conversation, agentName: this.agents.get(conversation.agentId)?.name ?? conversation.agentId, messageCount: messages.length, lastMessage: messages[0]?.content }; }); }
  async adminConversation(conversationId: string) { const conversation = this.conversations.get(conversationId); if (!conversation) return undefined; const rows = await this.adminConversations(this.conversations.size); const enriched = rows.find((item) => item.id === conversationId); return enriched ? { conversation: enriched, messages: await this.listMessages(conversationId) } : undefined; }
  async adminUsage(limit: number) { return [...this.usage.values()].sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, limit).map((event) => ({ ...event, agentName: this.agents.get(event.agentId)?.name ?? event.agentId })); }
  async adminDeployments(limit: number) { return [...this.deployments.values()].sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, limit).map(({ tokenHash: _tokenHash, ...deployment }) => ({ ...deployment, agentName: this.agents.get(deployment.agentId)?.name ?? deployment.agentId })); }
  async adminRevokeDeployment(deploymentId: string) { const deployment = this.deployments.get(deploymentId); if (!deployment) return false; this.deployments.set(deploymentId, { ...deployment, status: "revoked", updatedAt: new Date().toISOString() }); return true; }
  async adminKnowledge(limit: number) { return [...this.knowledge.values()].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)).slice(0, limit).map((source) => ({ ...source, agentName: this.agents.get(source.agentId)?.name ?? source.agentId })); }
  async adminTools() { return Object.entries(BUILTIN_TOOLS).map(([name, definition]) => ({ name, description: definition.function.description, agents: [...this.agents.values()].filter((agent) => agent.enabledTools.includes(name)).length, calls: [...this.usage.values()].filter((event) => event.toolCalls > 0).reduce((sum, event) => sum + event.toolCalls, 0) })); }
  async adminActivity(limit: number) { const activity: AdminActivity[] = []; for (const audit of this.audits.values()) activity.push({ id: audit.id, type: "audit", workspaceId: audit.workspaceId, agentId: audit.targetType === "agent" ? audit.targetId : undefined, description: `${audit.action} ${audit.targetType}`, status: "recorded", createdAt: audit.createdAt }); for (const event of this.usage.values()) activity.push({ id: event.requestId, type: "usage", workspaceId: event.workspaceId, agentId: event.agentId, agentName: this.agents.get(event.agentId)?.name, description: event.status === "completed" ? "AI response completed" : `Usage event ${event.status}`, status: event.status, createdAt: event.createdAt }); for (const conversation of this.conversations.values()) activity.push({ id: conversation.id, type: "conversation", workspaceId: conversation.workspaceId, agentId: conversation.agentId, agentName: this.agents.get(conversation.agentId)?.name, description: `Conversation ${conversation.status}`, status: conversation.status, createdAt: conversation.updatedAt }); for (const deployment of this.deployments.values()) activity.push({ id: deployment.id, type: "deployment", workspaceId: deployment.workspaceId, agentId: deployment.agentId, agentName: this.agents.get(deployment.agentId)?.name, description: `Website deployment ${deployment.status}`, status: deployment.status, createdAt: deployment.updatedAt }); return activity.sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, limit); }
}

class PostgresStore implements Store {
  constructor(private readonly pool: Pool) {}
  async listAgents(workspaceId: string) { const result = await this.pool.query("SELECT * FROM gbolix_agents WHERE workspace_id = $1 ORDER BY updated_at DESC", [workspaceId]); return result.rows.map((row) => agentRow(row)); }
  async createAgentVersion(input: Omit<AgentVersion, "id" | "createdAt">) { const result = await this.pool.query("INSERT INTO gbolix_agent_versions (id,agent_id,workspace_id,version,config,created_by) VALUES ($1,$2,$3,$4,$5,$6)", [id("ver"), input.agentId, input.workspaceId, input.version, JSON.stringify(input.config), input.createdBy]); return agentVersionRow({ id: id("ver"), agent_id: input.agentId, workspace_id: input.workspaceId, version: input.version, config: input.config, created_by: input.createdBy, created_at: now() }); }
  async listAgentVersions(agentId: string, workspaceId: string) { const result = await this.pool.query("SELECT * FROM gbolix_agent_versions WHERE agent_id=$1 AND workspace_id=$2 ORDER BY version DESC", [agentId, workspaceId]); return result.rows.map(agentVersionRow); }
  async restoreAgentVersion(versionId: string, agentId: string, workspaceId: string) { const result = await this.pool.query("SELECT config FROM gbolix_agent_versions WHERE id=$1 AND agent_id=$2 AND workspace_id=$3 LIMIT 1", [versionId, agentId, workspaceId]); const version = result.rows[0]; if (!version) return undefined; return this.updateAgent(agentId, workspaceId, version.config as AgentVersion["config"]); }
  async getAgent(agentId: string) { const result = await this.pool.query("SELECT * FROM gbolix_agents WHERE id = $1 LIMIT 1", [agentId]); return result.rows[0] ? agentRow(result.rows[0]) : undefined; }
  async createAgent(input: Omit<Agent, "id" | "createdAt" | "updatedAt">) { const result = await this.pool.query("INSERT INTO gbolix_agents (id, workspace_id, name, description, instructions, tone, model, level, status, welcome_message, enabled_tools) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *", [id("agent"), input.workspaceId, input.name, input.description, input.instructions, input.tone, input.model, input.level, input.status, input.welcomeMessage, JSON.stringify(input.enabledTools)]); return agentRow(result.rows[0]); }
  async updateAgent(agentId: string, workspaceId: string, patch: Partial<Pick<Agent, "name" | "description" | "instructions" | "tone" | "model" | "level" | "status" | "welcomeMessage" | "enabledTools">>) { const current = await this.getAgent(agentId); if (!current || current.workspaceId !== workspaceId) return undefined; const next = { ...current, ...patch, status: current.status ?? "draft" }; const result = await this.pool.query("UPDATE gbolix_agents SET name=$1, description=$2, instructions=$3, tone=$4, model=$5, level=$6, status=$7, welcome_message=$8, enabled_tools=$9, updated_at=NOW() WHERE id=$10 AND workspace_id=$11 RETURNING *", [next.name, next.description, next.instructions, next.tone, next.model, next.level, next.status, next.welcomeMessage, JSON.stringify(next.enabledTools), agentId, workspaceId]); return result.rows[0] ? agentRow(result.rows[0]) : undefined; }
  async listKnowledge(agentId: string, workspaceId: string) { const result = await this.pool.query("SELECT * FROM gbolix_knowledge WHERE agent_id=$1 AND workspace_id=$2 AND status='ready' ORDER BY updated_at DESC", [agentId, workspaceId]); return result.rows.map(knowledgeRow); }
  async addKnowledge(input: Omit<KnowledgeSource, "id" | "createdAt" | "updatedAt">) { const result = await this.pool.query("INSERT INTO gbolix_knowledge (id,agent_id,workspace_id,title,content,source_type,status) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING *", [id("know"), input.agentId, input.workspaceId, input.title, input.content, input.sourceType, input.status]); return knowledgeRow(result.rows[0]); }
  async deleteKnowledge(knowledgeId: string, agentId: string, workspaceId: string) { const result = await this.pool.query("DELETE FROM gbolix_knowledge WHERE id=$1 AND agent_id=$2 AND workspace_id=$3", [knowledgeId, agentId, workspaceId]); return result.rowCount === 1; }
  async getConversation(conversationId: string, workspaceId: string) { const result = await this.pool.query("SELECT * FROM gbolix_conversations WHERE id=$1 AND workspace_id=$2 LIMIT 1", [conversationId, workspaceId]); return result.rows[0] ? conversationRow(result.rows[0]) : undefined; }
  async listConversations(agentId: string, workspaceId: string) { const result = await this.pool.query("SELECT * FROM gbolix_conversations WHERE agent_id=$1 AND workspace_id=$2 ORDER BY updated_at DESC", [agentId, workspaceId]); return result.rows.map(conversationRow); }
  async createConversation(input: Omit<Conversation, "id" | "createdAt" | "updatedAt">) { const result = await this.pool.query("INSERT INTO gbolix_conversations (id,agent_id,workspace_id,channel,visitor_key,status) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *", [id("conv"), input.agentId, input.workspaceId, input.channel, input.visitorKey, input.status]); return conversationRow(result.rows[0]); }
  async touchConversation(conversationId: string, status?: ConversationStatus) { await this.pool.query("UPDATE gbolix_conversations SET status=COALESCE($1,status), updated_at=NOW() WHERE id=$2", [status ?? null, conversationId]); }
  async listMessages(conversationId: string) { const result = await this.pool.query("SELECT * FROM gbolix_messages WHERE conversation_id=$1 ORDER BY created_at ASC", [conversationId]); return result.rows.map(messageRow); }
  async addMessage(input: Omit<Message, "id" | "createdAt">) { const result = await this.pool.query("INSERT INTO gbolix_messages (id,conversation_id,role,content,tool_name) VALUES ($1,$2,$3,$4,$5) RETURNING *", [id("msg"), input.conversationId, input.role, input.content, input.toolName ?? null]); return messageRow(result.rows[0]); }
  async createDeployment(input: Omit<Deployment, "id" | "createdAt" | "updatedAt">) { const raw = crypto.randomBytes(24).toString("base64url"); const result = await this.pool.query("INSERT INTO gbolix_deployments (id,agent_id,workspace_id,channel,allowed_origin,token_prefix,public_token_hash,encrypted_public_token,status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *", [id("dep"), input.agentId, input.workspaceId, input.channel, input.allowedOrigin ?? null, `gblx_${raw.slice(0, 8)}`, hash(raw), sealDeploymentToken(raw), input.status]); return { ...deploymentRow(result.rows[0]), plaintextToken: raw }; }
  async listDeployments(agentId: string, workspaceId: string) { const result = await this.pool.query("SELECT * FROM gbolix_deployments WHERE agent_id=$1 AND workspace_id=$2 ORDER BY created_at DESC", [agentId, workspaceId]); return result.rows.map((row) => deploymentRow(row)); }
  async getDeploymentByToken(token: string) { const result = await this.pool.query("SELECT d.*, a.* FROM gbolix_deployments d JOIN gbolix_agents a ON a.id=d.agent_id WHERE d.public_token_hash=$1 AND d.status='active' LIMIT 1", [hash(token)]); if (!result.rows[0]) return undefined; return { deployment: deploymentRow(result.rows[0], "d_"), agent: agentRow(result.rows[0], "a_") }; }
  async getDeploymentArtifact(deploymentId: string, agentId: string, workspaceId: string) { const result = await this.pool.query("SELECT * FROM gbolix_deployments WHERE id=$1 AND agent_id=$2 AND workspace_id=$3 AND status='active' LIMIT 1", [deploymentId, agentId, workspaceId]); if (!result.rows[0]) return undefined; let raw = result.rows[0].encrypted_public_token ? openDeploymentToken(result.rows[0].encrypted_public_token) : undefined; if (!raw) { raw = crypto.randomBytes(24).toString("base64url"); const updated = await this.pool.query("UPDATE gbolix_deployments SET token_prefix=$4, public_token_hash=$5, encrypted_public_token=$6, updated_at=NOW() WHERE id=$1 AND agent_id=$2 AND workspace_id=$3 AND status='active' RETURNING *", [deploymentId, agentId, workspaceId, `gblx_${raw.slice(0, 8)}`, hash(raw), sealDeploymentToken(raw)]); if (!updated.rows[0]) return undefined; result.rows[0] = updated.rows[0]; } return { deployment: deploymentRow(result.rows[0]), plaintextToken: raw }; }
  async revokeDeployment(deploymentId: string, agentId: string, workspaceId: string) { const result = await this.pool.query("UPDATE gbolix_deployments SET status='revoked',updated_at=NOW() WHERE id=$1 AND agent_id=$2 AND workspace_id=$3", [deploymentId, agentId, workspaceId]); return result.rowCount === 1; }
  async adminRevokeDeployment(deploymentId: string) { const result = await this.pool.query("UPDATE gbolix_deployments SET status='revoked',updated_at=NOW() WHERE id=$1", [deploymentId]); return result.rowCount === 1; }
  async createApiKey(input: Omit<ApiKeyRecord, "id" | "createdAt">) { const result = await this.pool.query("INSERT INTO gbolix_api_keys (id,agent_id,workspace_id,key_prefix,key_hash,status) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *", [id("key"), input.agentId, input.workspaceId, input.keyPrefix, input.keyHash, input.status]); return apiKeyRow(result.rows[0]); }
  async getApiKeyByHash(keyHash: string) { const result = await this.pool.query("UPDATE gbolix_api_keys SET last_used_at=NOW() WHERE key_hash=$1 AND status='active' RETURNING *", [keyHash]); return result.rows[0] ? apiKeyRow(result.rows[0]) : undefined; }
  async listApiKeys(agentId: string, workspaceId: string) { const result = await this.pool.query("SELECT * FROM gbolix_api_keys WHERE agent_id=$1 AND workspace_id=$2 ORDER BY created_at DESC", [agentId, workspaceId]); return result.rows.map((row) => ({ ...apiKeyRow(row), keyHash: "" })); }
  async revokeApiKey(id: string, agentId: string, workspaceId: string) { const result = await this.pool.query("UPDATE gbolix_api_keys SET status='revoked' WHERE id=$1 AND agent_id=$2 AND workspace_id=$3", [id, agentId, workspaceId]); return result.rowCount === 1; }
  async createConnection(input: { agentId: string; workspaceId: string; kind: AgentConnection["kind"]; provider: string; name: string; endpoint?: string; method?: AgentConnection["method"]; authType?: AgentConnection["authType"]; encryptedSecret?: string; headers?: Record<string, string>; parameters?: Record<string, string>; permissions: string[] }) { const result = await this.pool.query("INSERT INTO gbolix_agent_connections (id,agent_id,workspace_id,kind,provider,name,endpoint,method,auth_type,encrypted_secret,headers,parameters,status,permissions) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,'connected',$13) RETURNING *", [id("conn"), input.agentId, input.workspaceId, input.kind, input.provider, input.name, input.endpoint ?? null, input.method ?? null, input.authType ?? null, input.encryptedSecret ?? null, JSON.stringify(input.headers ?? {}), JSON.stringify(input.parameters ?? {}), JSON.stringify(input.permissions)]); return connectionRow(result.rows[0]); }
  async listConnections(agentId: string, workspaceId: string) { const result = await this.pool.query("SELECT * FROM gbolix_agent_connections WHERE agent_id=$1 AND workspace_id=$2 ORDER BY updated_at DESC", [agentId, workspaceId]); return result.rows.map(connectionRow); }
  async getConnection(connectionId: string, agentId: string, workspaceId: string) { const result = await this.pool.query("SELECT * FROM gbolix_agent_connections WHERE id=$1 AND agent_id=$2 AND workspace_id=$3 LIMIT 1", [connectionId, agentId, workspaceId]); const row = result.rows[0]; return row ? { ...connectionRow(row), encryptedSecret: row.encrypted_secret ?? undefined, headers: row.headers ?? {}, parameters: row.parameters ?? {} } : undefined; }
  async updateConnectionSecret(connectionId: string, agentId: string, workspaceId: string, encryptedSecret: string) { const result = await this.pool.query("UPDATE gbolix_agent_connections SET encrypted_secret=$1, updated_at=NOW() WHERE id=$2 AND agent_id=$3 AND workspace_id=$4", [encryptedSecret, connectionId, agentId, workspaceId]); return result.rowCount === 1; }
  async deleteConnection(id: string, agentId: string, workspaceId: string) { const result = await this.pool.query("DELETE FROM gbolix_agent_connections WHERE id=$1 AND agent_id=$2 AND workspace_id=$3", [id, agentId, workspaceId]); return result.rowCount === 1; }
  async listAgentsWithEmailAutomation() { const result = await this.pool.query("SELECT a.* FROM gbolix_agents a JOIN gbolix_email_settings s ON s.agent_id=a.id WHERE s.reply_mode <> 'off'"); return result.rows.map((row) => agentRow(row)); }
  async getAiProviderSettings(agentId: string, workspaceId: string) { const result = await this.pool.query("SELECT * FROM gbolix_ai_provider_settings WHERE agent_id=$1 AND workspace_id=$2 LIMIT 1", [agentId, workspaceId]); return result.rows[0] ? aiProviderSettingsRow(result.rows[0]) : undefined; }
  async upsertAiProviderSettings(input: Omit<AiProviderSettings, "updatedAt">) { const result = await this.pool.query("INSERT INTO gbolix_ai_provider_settings (agent_id,workspace_id,provider_order,models,fallback_enabled,auto_update_models) VALUES ($1,$2,$3,$4,$5,$6) ON CONFLICT (agent_id) DO UPDATE SET workspace_id=EXCLUDED.workspace_id,provider_order=EXCLUDED.provider_order,models=EXCLUDED.models,fallback_enabled=EXCLUDED.fallback_enabled,auto_update_models=EXCLUDED.auto_update_models,updated_at=NOW() RETURNING *", [input.agentId, input.workspaceId, JSON.stringify(input.providerOrder), JSON.stringify(input.models), input.fallbackEnabled, input.autoUpdateModels]); return aiProviderSettingsRow(result.rows[0]); }
  async listAiProviders() { const result = await this.pool.query("SELECT * FROM gbolix_ai_providers ORDER BY priority ASC, name ASC"); return result.rows.map(aiProviderRow); }
  async listAiProviderSecrets() { const result = await this.pool.query("SELECT * FROM gbolix_ai_providers ORDER BY priority ASC, name ASC"); return result.rows.map(aiProviderSecretRow); }
  async getAiProvider(providerId: string) { const result = await this.pool.query("SELECT * FROM gbolix_ai_providers WHERE id=$1 LIMIT 1", [providerId]); return result.rows[0] ? aiProviderSecretRow(result.rows[0]) : undefined; }
  async upsertAiProvider(input: { id: string; name: string; adapter: AiProviderAdapter; baseUrl: string; encryptedApiKey?: string; defaultModel: string; priority: number; enabled: boolean }) { const result = await this.pool.query("INSERT INTO gbolix_ai_providers (id,name,adapter,base_url,encrypted_api_key,default_model,priority,enabled) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,adapter=EXCLUDED.adapter,base_url=EXCLUDED.base_url,encrypted_api_key=COALESCE(EXCLUDED.encrypted_api_key,gbolix_ai_providers.encrypted_api_key),default_model=EXCLUDED.default_model,priority=EXCLUDED.priority,enabled=EXCLUDED.enabled,updated_at=NOW() RETURNING *", [input.id, input.name, input.adapter, input.baseUrl, input.encryptedApiKey ?? null, input.defaultModel, input.priority, input.enabled]); return aiProviderRow(result.rows[0]); }
  async deleteAiProvider(providerId: string) { const result = await this.pool.query("DELETE FROM gbolix_ai_providers WHERE id=$1", [providerId]); return result.rowCount === 1; }
  async getEmailSettings(agentId: string, workspaceId: string) { const result = await this.pool.query("SELECT * FROM gbolix_email_settings WHERE agent_id=$1 AND workspace_id=$2", [agentId, workspaceId]); return result.rows[0] ? emailSettingsRow(result.rows[0]) : undefined; }
  async upsertEmailSettings(input: Omit<EmailSettings, "updatedAt">) { const result = await this.pool.query("INSERT INTO gbolix_email_settings (agent_id,workspace_id,reply_mode,reply_scope,matching_query) VALUES ($1,$2,$3,$4,$5) ON CONFLICT (agent_id) DO UPDATE SET workspace_id=EXCLUDED.workspace_id,reply_mode=EXCLUDED.reply_mode,reply_scope=EXCLUDED.reply_scope,matching_query=EXCLUDED.matching_query,updated_at=NOW() RETURNING *", [input.agentId, input.workspaceId, input.replyMode, input.replyScope, input.matchingQuery]); return emailSettingsRow(result.rows[0]); }
  async createEmailCampaign(input: Omit<EmailCampaign, "id" | "createdAt" | "updatedAt" | "sentRows" | "failedRows">) { const result = await this.pool.query("INSERT INTO gbolix_email_campaigns (id,agent_id,workspace_id,status,subject_template,body_template,message_mode,total_rows) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *", [id("campaign"), input.agentId, input.workspaceId, input.status, input.subjectTemplate, input.bodyTemplate, input.messageMode, input.totalRows]); return emailCampaignRow(result.rows[0]); }
  async listEmailCampaigns(agentId: string, workspaceId: string, limit: number) { const result = await this.pool.query("SELECT * FROM gbolix_email_campaigns WHERE agent_id=$1 AND workspace_id=$2 ORDER BY created_at DESC LIMIT $3", [agentId, workspaceId, limit]); return result.rows.map(emailCampaignRow); }
  async getEmailCampaign(campaignId: string, agentId: string, workspaceId: string) { const result = await this.pool.query("SELECT * FROM gbolix_email_campaigns WHERE id=$1 AND agent_id=$2 AND workspace_id=$3", [campaignId, agentId, workspaceId]); return result.rows[0] ? emailCampaignRow(result.rows[0]) : undefined; }
  async updateEmailCampaign(campaignId: string, agentId: string, workspaceId: string, patch: Partial<Pick<EmailCampaign, "status" | "sentRows" | "failedRows" | "totalRows">>) { const current = await this.getEmailCampaign(campaignId, agentId, workspaceId); if (!current) return undefined; const next = { ...current, ...patch }; const result = await this.pool.query("UPDATE gbolix_email_campaigns SET status=$1,total_rows=$2,sent_rows=$3,failed_rows=$4,updated_at=NOW() WHERE id=$5 AND agent_id=$6 AND workspace_id=$7 RETURNING *", [next.status, next.totalRows, next.sentRows, next.failedRows, campaignId, agentId, workspaceId]); return result.rows[0] ? emailCampaignRow(result.rows[0]) : undefined; }
  async addEmailCampaignRows(rows: Array<Omit<EmailCampaignRow, "id" | "createdAt" | "updatedAt">>) { const result = []; for (const input of rows) { const row = await this.pool.query("INSERT INTO gbolix_email_campaign_rows (id,campaign_id,row_number,email,data,subject,body,status,message_id,thread_id,error) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT (campaign_id,row_number) DO UPDATE SET email=EXCLUDED.email,data=EXCLUDED.data,subject=EXCLUDED.subject,body=EXCLUDED.body,status=EXCLUDED.status RETURNING *", [id("campaign_row"), input.campaignId, input.rowNumber, input.email, JSON.stringify(input.data), input.subject, input.body, input.status, input.messageId ?? null, input.threadId ?? null, input.error ?? null]); result.push(emailCampaignRowItem(row.rows[0])); } return result; }
  async listEmailCampaignRows(campaignId: string, limit: number) { const result = await this.pool.query("SELECT * FROM gbolix_email_campaign_rows WHERE campaign_id=$1 ORDER BY row_number LIMIT $2", [campaignId, limit]); return result.rows.map(emailCampaignRowItem); }
  async updateEmailCampaignRow(rowId: string, campaignId: string, patch: Partial<Pick<EmailCampaignRow, "status" | "messageId" | "threadId" | "error">>) { const current = await this.pool.query("SELECT * FROM gbolix_email_campaign_rows WHERE id=$1 AND campaign_id=$2", [rowId, campaignId]); if (!current.rows[0]) return undefined; const value = emailCampaignRowItem(current.rows[0]); const next = { ...value, ...patch }; const result = await this.pool.query("UPDATE gbolix_email_campaign_rows SET status=$1,message_id=$2,thread_id=$3,error=$4,updated_at=NOW() WHERE id=$5 AND campaign_id=$6 RETURNING *", [next.status, next.messageId ?? null, next.threadId ?? null, next.error ?? null, rowId, campaignId]); return result.rows[0] ? emailCampaignRowItem(result.rows[0]) : undefined; }
  async getEmailReplyEvent(agentId: string, gmailMessageId: string) { const result = await this.pool.query("SELECT * FROM gbolix_email_reply_events WHERE agent_id=$1 AND gmail_message_id=$2", [agentId, gmailMessageId]); return result.rows[0] ? emailReplyEventRow(result.rows[0]) : undefined; }
  async createEmailReplyEvent(input: Omit<EmailReplyEvent, "id" | "createdAt" | "updatedAt">) { const result = await this.pool.query("INSERT INTO gbolix_email_reply_events (id,agent_id,workspace_id,gmail_message_id,thread_id,from_email,subject,received_at,body,status,reply_body,reply_message_id,error) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT (agent_id,gmail_message_id) DO UPDATE SET gmail_message_id=EXCLUDED.gmail_message_id RETURNING *", [id("reply"), input.agentId, input.workspaceId, input.gmailMessageId, input.threadId, input.fromEmail ?? null, input.subject ?? null, input.receivedAt ?? null, input.body, input.status, input.replyBody ?? null, input.replyMessageId ?? null, input.error ?? null]); return emailReplyEventRow(result.rows[0]); }
  async updateEmailReplyEvent(eventId: string, agentId: string, patch: Partial<Pick<EmailReplyEvent, "status" | "replyBody" | "replyMessageId" | "error">>) { const current = await this.pool.query("SELECT * FROM gbolix_email_reply_events WHERE id=$1 AND agent_id=$2", [eventId, agentId]); if (!current.rows[0]) return undefined; const value = emailReplyEventRow(current.rows[0]); const next = { ...value, ...patch }; const result = await this.pool.query("UPDATE gbolix_email_reply_events SET status=$1,reply_body=$2,reply_message_id=$3,error=$4,updated_at=NOW() WHERE id=$5 AND agent_id=$6 RETURNING *", [next.status, next.replyBody ?? null, next.replyMessageId ?? null, next.error ?? null, eventId, agentId]); return result.rows[0] ? emailReplyEventRow(result.rows[0]) : undefined; }
  async listEmailReplyEvents(agentId: string, workspaceId: string, limit: number) { const result = await this.pool.query("SELECT * FROM gbolix_email_reply_events WHERE agent_id=$1 AND workspace_id=$2 ORDER BY updated_at DESC LIMIT $3", [agentId, workspaceId, limit]); return result.rows.map(emailReplyEventRow); }
  async addUsageEvent(event: UsageEvent) { const result = await this.pool.query("INSERT INTO gbolix_usage_events (request_id,workspace_id,agent_id,conversation_id,model,input_tokens,output_tokens,tool_calls,credits,status,channel) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT (request_id) DO UPDATE SET request_id=EXCLUDED.request_id RETURNING *", [event.requestId, event.workspaceId, event.agentId, event.conversationId, event.model, event.inputTokens, event.outputTokens, event.toolCalls, event.credits, event.status, event.channel]); return usageRow(result.rows[0]); }
  async listUsage(agentId: string, workspaceId: string, limit: number) { const result = await this.pool.query("SELECT * FROM gbolix_usage_events WHERE agent_id=$1 AND workspace_id=$2 ORDER BY created_at DESC LIMIT $3", [agentId, workspaceId, limit]); return result.rows.map(usageRow); }
  async addAuditEvent(event: Omit<AuditEvent, "id" | "createdAt">) { const result = await this.pool.query("INSERT INTO gbolix_audit_logs (id,actor_id,workspace_id,action,target_type,target_id,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING *", [id("audit"), event.actorId, event.workspaceId, event.action, event.targetType, event.targetId, JSON.stringify(event.metadata)]); return auditRow(result.rows[0]); }
  async listAudit(workspaceId: string, limit: number) { const result = await this.pool.query("SELECT * FROM gbolix_audit_logs WHERE workspace_id=$1 ORDER BY created_at DESC LIMIT $2", [workspaceId, limit]); return result.rows.map(auditRow); }
  async adminOverview() { const result = await this.pool.query("SELECT COUNT(DISTINCT workspace_id)::int AS customers, COUNT(DISTINCT agent_id)::int AS agents, COUNT(*) FILTER (WHERE status='completed')::int AS responses, COALESCE(SUM(credits),0)::int AS credits_used, (SELECT COUNT(*)::int FROM gbolix_deployments WHERE status='active') AS deployments FROM gbolix_usage_events"); return result.rows[0]; }
  async adminCustomers(limit: number) { const result = await this.pool.query("SELECT a.workspace_id, COUNT(DISTINCT a.id)::int AS agents, COUNT(u.request_id) FILTER (WHERE u.status='completed')::int AS responses, COALESCE(SUM(u.credits),0)::int AS credits_used FROM gbolix_agents a LEFT JOIN gbolix_usage_events u ON u.agent_id=a.id GROUP BY a.workspace_id ORDER BY responses DESC, a.workspace_id LIMIT $1", [limit]); return result.rows.map((row) => ({ workspaceId: row.workspace_id, agents: row.agents, responses: row.responses, creditsUsed: row.credits_used })); }
  async adminAgents(limit: number) { const result = await this.pool.query("SELECT a.*, (SELECT COUNT(*)::int FROM gbolix_knowledge k WHERE k.agent_id=a.id) AS knowledge_count, (SELECT COUNT(*)::int FROM gbolix_conversations c WHERE c.agent_id=a.id) AS conversation_count, (SELECT COUNT(*)::int FROM gbolix_usage_events u WHERE u.agent_id=a.id AND u.status='completed') AS responses, (SELECT COALESCE(SUM(u.credits),0)::int FROM gbolix_usage_events u WHERE u.agent_id=a.id) AS credits_used, (SELECT COUNT(*)::int FROM gbolix_deployments d WHERE d.agent_id=a.id) AS deployment_count FROM gbolix_agents a ORDER BY a.updated_at DESC LIMIT $1", [limit]); return result.rows.map((row) => ({ ...agentRow(row), knowledgeCount: row.knowledge_count, conversationCount: row.conversation_count, responses: row.responses, creditsUsed: row.credits_used, deploymentCount: row.deployment_count })); }
  async adminConversations(limit: number) { const result = await this.pool.query("SELECT c.*, a.name AS agent_name, COUNT(m.id)::int AS message_count, (SELECT m2.content FROM gbolix_messages m2 WHERE m2.conversation_id=c.id ORDER BY m2.created_at DESC LIMIT 1) AS last_message FROM gbolix_conversations c JOIN gbolix_agents a ON a.id=c.agent_id LEFT JOIN gbolix_messages m ON m.conversation_id=c.id GROUP BY c.id, a.name ORDER BY c.updated_at DESC LIMIT $1", [limit]); return result.rows.map((row) => ({ ...conversationRow(row), agentName: row.agent_name, messageCount: row.message_count, lastMessage: row.last_message ?? undefined })); }
  async adminConversation(conversationId: string) { const result = await this.pool.query("SELECT c.*, a.name AS agent_name, COUNT(m.id)::int AS message_count, (SELECT m2.content FROM gbolix_messages m2 WHERE m2.conversation_id=c.id ORDER BY m2.created_at DESC LIMIT 1) AS last_message FROM gbolix_conversations c JOIN gbolix_agents a ON a.id=c.agent_id LEFT JOIN gbolix_messages m ON m.conversation_id=c.id WHERE c.id=$1 GROUP BY c.id, a.name LIMIT 1", [conversationId]); if (!result.rows[0]) return undefined; const messages = await this.pool.query("SELECT * FROM gbolix_messages WHERE conversation_id=$1 ORDER BY created_at ASC", [conversationId]); return { conversation: { ...conversationRow(result.rows[0]), agentName: result.rows[0].agent_name, messageCount: result.rows[0].message_count, lastMessage: result.rows[0].last_message ?? undefined }, messages: messages.rows.map(messageRow) }; }
  async adminUsage(limit: number) { const result = await this.pool.query("SELECT u.*, a.name AS agent_name FROM gbolix_usage_events u JOIN gbolix_agents a ON a.id=u.agent_id ORDER BY u.created_at DESC LIMIT $1", [limit]); return result.rows.map((row) => ({ ...usageRow(row), agentName: row.agent_name })); }
  async adminDeployments(limit: number) { const result = await this.pool.query("SELECT d.*, a.name AS agent_name FROM gbolix_deployments d JOIN gbolix_agents a ON a.id=d.agent_id ORDER BY d.created_at DESC LIMIT $1", [limit]); return result.rows.map((row) => ({ ...deploymentRow(row), agentName: row.agent_name })); }
  async adminKnowledge(limit: number) { const result = await this.pool.query("SELECT k.*, a.name AS agent_name FROM gbolix_knowledge k JOIN gbolix_agents a ON a.id=k.agent_id ORDER BY k.updated_at DESC LIMIT $1", [limit]); return result.rows.map((row) => ({ ...knowledgeRow(row), agentName: row.agent_name })); }
  async adminTools() { const result = await this.pool.query("SELECT a.enabled_tools FROM gbolix_agents a"); const adoption = new Map<string, number>(); for (const row of result.rows) { const tools = Array.isArray(row.enabled_tools) ? row.enabled_tools : []; for (const tool of tools) adoption.set(tool, (adoption.get(tool) ?? 0) + 1); } const calls = await this.pool.query("SELECT COALESCE(SUM(tool_calls),0)::int AS total_calls FROM gbolix_usage_events"); return Object.entries(BUILTIN_TOOLS).map(([name, definition]) => ({ name, description: definition.function.description, agents: adoption.get(name) ?? 0, calls: calls.rows[0]?.total_calls ?? 0 })); }
  async adminActivity(limit: number) { const result = await this.pool.query("SELECT id, type, workspace_id, agent_id, agent_name, description, status, created_at FROM (SELECT u.request_id AS id, 'usage' AS type, u.workspace_id, u.agent_id, a.name AS agent_name, CASE WHEN u.status='completed' THEN 'AI response completed' ELSE 'Usage event ' || u.status END AS description, u.status, u.created_at FROM gbolix_usage_events u JOIN gbolix_agents a ON a.id=u.agent_id UNION ALL SELECT c.id, 'conversation' AS type, c.workspace_id, c.agent_id, a.name AS agent_name, 'Conversation ' || c.status AS description, c.status, c.updated_at AS created_at FROM gbolix_conversations c JOIN gbolix_agents a ON a.id=c.agent_id UNION ALL SELECT d.id, 'deployment' AS type, d.workspace_id, d.agent_id, a.name AS agent_name, 'Website deployment ' || d.status AS description, d.status, d.updated_at AS created_at FROM gbolix_deployments d JOIN gbolix_agents a ON a.id=d.agent_id UNION ALL SELECT l.id, 'audit' AS type, l.workspace_id, CASE WHEN l.target_type='agent' THEN l.target_id ELSE NULL END AS agent_id, NULL::text AS agent_name, l.action || ' ' || l.target_type AS description, 'recorded' AS status, l.created_at FROM gbolix_audit_logs l) activity ORDER BY created_at DESC LIMIT $1", [limit]); return result.rows.map((row) => ({ id: row.id, type: row.type, workspaceId: row.workspace_id, agentId: row.agent_id, agentName: row.agent_name, description: row.description, status: row.status, createdAt: new Date(row.created_at).toISOString() })); }
}

function hash(value: string) { return crypto.createHash("sha256").update(value).digest("hex"); }
function sealDeploymentToken(value: string): string { if (!config.connectionEncryptionKey) throw new Error("AGENT_CONNECTION_ENCRYPTION_KEY is required before storing deployment tokens."); const key = crypto.createHash("sha256").update(config.connectionEncryptionKey).digest(); const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv("aes-256-gcm", key, iv); const ciphertext = Buffer.concat([cipher.update(value, "utf8"), cipher.final()]); return `v1:${iv.toString("base64url")}:${cipher.getAuthTag().toString("base64url")}:${ciphertext.toString("base64url")}`; }
function openDeploymentToken(value: string): string { if (!config.connectionEncryptionKey) throw new Error("AGENT_CONNECTION_ENCRYPTION_KEY is required before reading deployment tokens."); const [version, ivValue, tagValue, ciphertextValue] = value.split(":"); if (version !== "v1" || !ivValue || !tagValue || !ciphertextValue) throw new Error("Invalid deployment token format."); const key = crypto.createHash("sha256").update(config.connectionEncryptionKey).digest(); const decipher = crypto.createDecipheriv("aes-256-gcm", key, Buffer.from(ivValue, "base64url")); decipher.setAuthTag(Buffer.from(tagValue, "base64url")); return Buffer.concat([decipher.update(Buffer.from(ciphertextValue, "base64url")), decipher.final()]).toString("utf8"); }
function agentVersionRow(row: any): AgentVersion { return { id: row.id, agentId: row.agent_id, workspaceId: row.workspace_id, version: row.version, config: row.config, createdBy: row.created_by, createdAt: new Date(row.created_at).toISOString() }; }
function agentRow(row: any, prefix = ""): Agent { return { id: row[`${prefix}id`] ?? row.id, workspaceId: row[`${prefix}workspace_id`] ?? row.workspace_id, name: row[`${prefix}name`] ?? row.name, description: row[`${prefix}description`] ?? row.description, instructions: row[`${prefix}instructions`] ?? row.instructions, tone: row[`${prefix}tone`] ?? row.tone, model: row[`${prefix}model`] ?? row.model, level: (row[`${prefix}level`] ?? row.level ?? 1) as Agent["level"], status: row[`${prefix}status`] ?? row.status ?? "draft", welcomeMessage: row[`${prefix}welcome_message`] ?? row.welcome_message, enabledTools: row[`${prefix}enabled_tools`] ?? row.enabled_tools ?? [], createdAt: new Date(row[`${prefix}created_at`] ?? row.created_at).toISOString(), updatedAt: new Date(row[`${prefix}updated_at`] ?? row.updated_at).toISOString() }; }
function knowledgeRow(row: any): KnowledgeSource { return { id: row.id, agentId: row.agent_id, workspaceId: row.workspace_id, title: row.title, content: row.content, sourceType: row.source_type, status: row.status, createdAt: new Date(row.created_at).toISOString(), updatedAt: new Date(row.updated_at).toISOString() }; }
function conversationRow(row: any): Conversation { return { id: row.id, agentId: row.agent_id, workspaceId: row.workspace_id, channel: row.channel, visitorKey: row.visitor_key, status: row.status, createdAt: new Date(row.created_at).toISOString(), updatedAt: new Date(row.updated_at).toISOString() }; }
function messageRow(row: any): Message { return { id: row.id, conversationId: row.conversation_id, role: row.role, content: row.content, toolName: row.tool_name ?? undefined, createdAt: new Date(row.created_at).toISOString() }; }
function deploymentRow(row: any, prefix = ""): Deployment { return { id: row[`${prefix}id`] ?? row.id, agentId: row[`${prefix}agent_id`] ?? row.agent_id, workspaceId: row[`${prefix}workspace_id`] ?? row.workspace_id, channel: row[`${prefix}channel`] ?? row.channel, allowedOrigin: row[`${prefix}allowed_origin`] ?? row.allowed_origin ?? undefined, tokenPrefix: row[`${prefix}token_prefix`] ?? row.token_prefix, status: row[`${prefix}status`] ?? row.status, createdAt: new Date(row[`${prefix}created_at`] ?? row.created_at).toISOString(), updatedAt: new Date(row[`${prefix}updated_at`] ?? row.updated_at).toISOString() }; }
function connectionRow(row: any): AgentConnection { return { id: row.id, agentId: row.agent_id, workspaceId: row.workspace_id, kind: row.kind, provider: row.provider, name: row.name, endpoint: row.endpoint ?? undefined, method: row.method ?? undefined, authType: row.auth_type ?? undefined, status: row.status, permissions: Array.isArray(row.permissions) ? row.permissions : [], createdAt: new Date(row.created_at).toISOString(), updatedAt: new Date(row.updated_at).toISOString() }; }
function apiKeyRow(row: any): ApiKeyRecord { return { id: row.id, agentId: row.agent_id, workspaceId: row.workspace_id, keyPrefix: row.key_prefix, keyHash: row.key_hash, status: row.status, createdAt: new Date(row.created_at).toISOString(), lastUsedAt: row.last_used_at ? new Date(row.last_used_at).toISOString() : undefined }; }
function auditRow(row: any): AuditEvent { return { id: row.id, actorId: row.actor_id, workspaceId: row.workspace_id, action: row.action, targetType: row.target_type, targetId: row.target_id, metadata: row.metadata ?? {}, createdAt: new Date(row.created_at).toISOString() }; }
function usageRow(row: any): UsageEvent { return { requestId: row.request_id, workspaceId: row.workspace_id, agentId: row.agent_id, conversationId: row.conversation_id, model: row.model, inputTokens: row.input_tokens, outputTokens: row.output_tokens, toolCalls: row.tool_calls, credits: row.credits, status: row.status, channel: row.channel, createdAt: new Date(row.created_at).toISOString() }; }
function emailSettingsRow(row: any): EmailSettings { return { agentId: row.agent_id, workspaceId: row.workspace_id, replyMode: row.reply_mode, replyScope: row.reply_scope, matchingQuery: row.matching_query ?? "", updatedAt: new Date(row.updated_at).toISOString() }; }
function aiProviderRow(row: any): AiProvider { return { id: row.id, name: row.name, adapter: row.adapter, baseUrl: row.base_url, apiKeyConfigured: Boolean(row.encrypted_api_key), defaultModel: row.default_model, priority: Number(row.priority ?? 100), enabled: row.enabled !== false, createdAt: new Date(row.created_at).toISOString(), updatedAt: new Date(row.updated_at).toISOString() }; }
function aiProviderSecretRow(row: any): StoredAiProvider { return { ...aiProviderRow(row), encryptedApiKey: row.encrypted_api_key ?? undefined }; }
function aiProviderSettingsRow(row: any): AiProviderSettings { const providerOrder: AiProviderSettings["providerOrder"] = Array.isArray(row.provider_order) ? row.provider_order.filter((item: unknown): item is "gemini" | "openai" => item === "gemini" || item === "openai") : ["gemini", "openai"]; const models = row.models && typeof row.models === "object" && !Array.isArray(row.models) ? row.models : {}; return { agentId: row.agent_id, workspaceId: row.workspace_id, providerOrder: [...new Set(providerOrder)] as AiProviderSettings["providerOrder"], models, fallbackEnabled: row.fallback_enabled !== false, autoUpdateModels: row.auto_update_models !== false, updatedAt: new Date(row.updated_at).toISOString() }; }
function emailCampaignRow(row: any): EmailCampaign { return { id: row.id, agentId: row.agent_id, workspaceId: row.workspace_id, status: row.status, subjectTemplate: row.subject_template, bodyTemplate: row.body_template, messageMode: row.message_mode, totalRows: Number(row.total_rows ?? 0), sentRows: Number(row.sent_rows ?? 0), failedRows: Number(row.failed_rows ?? 0), createdAt: new Date(row.created_at).toISOString(), updatedAt: new Date(row.updated_at).toISOString() }; }
function emailCampaignRowItem(row: any): EmailCampaignRow { return { id: row.id, campaignId: row.campaign_id, rowNumber: Number(row.row_number), email: row.email, data: row.data ?? {}, subject: row.subject, body: row.body, status: row.status, messageId: row.message_id ?? undefined, threadId: row.thread_id ?? undefined, error: row.error ?? undefined, createdAt: new Date(row.created_at).toISOString(), updatedAt: new Date(row.updated_at).toISOString() }; }
function emailReplyEventRow(row: any): EmailReplyEvent { return { id: row.id, agentId: row.agent_id, workspaceId: row.workspace_id, gmailMessageId: row.gmail_message_id, threadId: row.thread_id, fromEmail: row.from_email ?? undefined, subject: row.subject ?? undefined, receivedAt: row.received_at ? new Date(row.received_at).toISOString() : undefined, body: row.body, status: row.status, replyBody: row.reply_body ?? undefined, replyMessageId: row.reply_message_id ?? undefined, error: row.error ?? undefined, createdAt: new Date(row.created_at).toISOString(), updatedAt: new Date(row.updated_at).toISOString() }; }

export async function createStore(): Promise<Store> {
  if (!config.databaseUrl) {
    if (process.env.NODE_ENV === "production" && !config.allowMemoryStorage) throw new Error("DATABASE_URL is required in production. Refusing to start with temporary in-memory storage.");
    return new MemoryStore();
  }
  const pool = new Pool({ connectionString: config.databaseUrl, ssl: config.databaseUrl.includes("localhost") ? false : { rejectUnauthorized: false } });
  await ensureSchema(pool);
  return new PostgresStore(pool);
}

export { hash };
